### ISSUE TITLE
Remember layout in cookies

### ISSUE THREAD

**Issue by P1llus** [tprobinson/aersia#1]
Hello!

Thanks for this great player, i use it everyday for work, and sometimes when streaming and such. I would love to not need to set the layout every time i open the stream on your github.io version. Would it be possible to set chosen layout in a cookie maybe?

**Comment by tprobinson** [comment]
Hey, thanks!

Actually, the player was supposed to already be doing this. Turns out I broke it and didn't notice, now it's fixed. You may need to hard reload the page to get your browser to notice the changes, by pressing Ctrl + Shift + R.
